  'use client'
 import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Suspense, useEffect, useState } from "react";
import { Toaster } from "sonner";
import { usePathname } from "next/navigation";

import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathname = usePathname()

   const isStudio = pathname.startsWith("/studio")
    const isHome = pathname.startsWith("/sign-in")
   const isAdmin = pathname.startsWith("/admin")
   const isOrders = pathname.startsWith("/orders");
   const isCustomers = pathname.startsWith("/customers");
   const isStatistics = pathname.startsWith("/product-data");
   const isReviews = pathname.startsWith("/reviews");
    
     const studioAndHome = !isStudio && !isHome && !isAdmin && !isOrders && !isCustomers && !isStatistics && !isReviews

  
   const [isLoading, setIsLoading] = useState(true)
  
    useEffect(() => {
      const timer = setTimeout(() => {
        setIsLoading(false)
       }, 2000) // 2 seconds delay
      return () => clearTimeout(timer)
     }, [pathname])


  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
      <Toaster richColors />
             {studioAndHome}
      {isLoading ? <Loading/> : <Suspense fallback={<Loading />}>{children}</Suspense>}
           {studioAndHome} 
        </body>
    </html>
    </ClerkProvider>
  );
}
